name: 'cut-release'
on:
  workflow_call:
    inputs:
      bump-level:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      bump-level:
        type: choice
        description: Bump level
        required: true
        default: auto
        options:
        - none
        - auto
        - patch
        - minor
        - major
      should-release:
        type: boolean
        description: Run release-app workflow
        required: false
        default: true
jobs:
  cut-release:
    if: github.ref_name == 'development'
    runs-on: ubuntu-latest
    steps:
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn --frozen-lockfile --production=false
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com" && git config --global user.name "github-actions[bot]"
      - name: Bump version (${{ github.event.inputs.bump-level }})
        if: github.event.inputs.bump-level != 'none'
        run: yarn bump ${{ github.event.inputs.bump-level }}
        env:
          TERM: xterm
      - name: Push bumped version
        if: github.event.inputs.bump-level != 'none'
        run: git push && git push --tags
  release-app:
    if: github.event.inputs.should-release == true
    needs: cut-release
    uses: ./.github/workflows/release-app.yml
    secrets: inherit