name: 'publish'
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup cache
        uses: ./.github/actions/cache
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install aarch64 dependencies
        run: rustup target add aarch64-apple-darwin
      - name: Install app dependencies
        run: yarn --frozen-lockfile
      - name: Release tauri darwin
        uses: tauri-apps/tauri-action@dev
        id: tauri-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: --target x86_64-apple-darwin
      - name: Print release url
        run: echo "[View release](${{ steps.tauri-action.outputs.releaseHtmlUrl }})" >> $GITHUB_STEP_SUMMARY
      - name: Clean release folder
        run: rm -rf ${{ github.workspace }}/src-tauri/target/release/bundle
      - name: Release tauri aarch64
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          releaseId: ${{ steps.tauri-action.outputs.releaseId }}
          args: --target aarch64-apple-darwin