name: 'Release app'

on:
  workflow_dispatch:

jobs:
  create-release:
    uses: ./.github/workflows/create-release.yml
  build-release:
    needs: create-release
    uses: ./.github/workflows/build-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
  publish-release:
    needs: [create-release, build-release]
    uses: ./.github/workflows/publish-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
    