name: 'Release app'

on:
  workflow_dispatch:

jobs:
  create-release:
    uses: ./.github/workflows/create-release.yml
    secrets: inherit
  build-release:
    needs: create-release
    uses: ./.github/workflows/build-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
    secrets: inherit
  publish-release:
    needs: [create-release, build-release]
    uses: ./.github/workflows/publish-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
    secrets: inherit
  update-release-branch:
    needs: [create-release, publish-release]
    uses: ./.github/workflows/update-release-branch.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
      tag: ${{ needs.create-release.outputs.tag }}
    secrets: inherit
    