name: 'Valid commit messages'

on: 
  pull_request:
  push:
    branches:
      - 'development'
jobs:
  verify-emoji-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm_verify_emoji_commit-${{ hashFiles('.github/workflows/.scripts/package-lock.json') }}
          restore-keys: 
            npm_verify_emoji_commit-${{ hashFiles('.github/workflows/.scripts/package-lock.json') }}
            npm_verify_emoji_commit-
      - name: Install verify-emoji-commit
        uses: baptiste0928/cargo-install@v1
        with:
          crate: verify-emoji-commit
          version: "0.2.0"
      - run: cd ./.github/workflows/.scripts && npm install
      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobid
        with:
          github_token: ${{ secrets.ACTIONS_READ_GITHUB_TOKEN }}
          job_name: ${{ github.job }}
      - name: Verify pushed commit messages 
        uses: actions/github-script@v6
        with:
          script: |
            const { default: verifyEmojiCommits } = await import('${{ github.workspace }}/.github/workflows/.scripts/verify-emoji-commits.js')
            const ref = '${{ github.head_ref || github.base_ref || github.ref }}'
            console.log('ref', ref)
            const jobUrl = '${{ steps.jobid.outputs.html_url }}'
        
            await verifyEmojiCommits({ jobUrl, ref, github, context, core })