name: 'validate-commits'

on: [pull_request]

jobs:
  verify-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/install@v0.1
        with:
          crate: verify-emoji-commit
          version: latest
      - name: Verify commit messages
        run: |
          git log --oneline ${{ github.base_ref }}..${{ github.head_ref }} | xargs -L1 verify-emoji-commit