name: 'Valid commit messages'

on: 
  pull_request:
  push:
    branches:
      - 'development'
jobs:
  verify-emoji-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm_verify_emoji_commit-${{ hashFiles('.github/workflows/.scripts/package-lock.json') }}
          restore-keys: 
            npm_verify_emoji_commit-${{ hashFiles('.github/workflows/.scripts/package-lock.json') }}
            npm_verify_emoji_commit-
      - name: Install verify-emoji-commit
        uses: baptiste0928/cargo-install@v1
        with:
          crate: verify-emoji-commit
          version: "0.1.1"
      - run: cd ./.github/workflows/.scripts && npm install
      - name: Verify pushed commit messages 
        uses: actions/github-script@v6
        with:
          script: |
            const { default: verifyEmojiCommits } = await import('${{ github.workspace }}/.github/workflows/.scripts/verify-emoji-commits.js')
            const ref = '${{ github.base_ref || github.ref  }}'
            await verifyEmojiCommits({ ref, github, context, core })
            
      # const statues = await github.rest.listCommitStatusesForRef({
      #   owner: context.repo.owner,
      #   repo: context.repo.repo,
      #   ref: process.env.COMMITS_REF
      # })
   
      # - name: Verify pushed commit messages
      #   if: ${{ github.event_name == 'pull_request' }}
      #   env:
      #     CLICOLOR_FORCE: true
      #   run: |
      #     git fetch origin ${{ github.base_ref }}
      #     git log --no-merges --skip 0 --oneline origin/${{ github.base_ref }}..HEAD | xargs -L1 verify-emoji-commit