name: 'validate-commits'

on: [pull_request]

jobs:
  verify-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install verify-emoji-commit
        uses: baptiste0928/cargo-install@v1
        with:
          crate: verify-emoji-commit
          version: "0.1.0"
      - name: Verify commit messages
        run: |
          git log --oneline ${{ github.base_ref }}..${{ github.head_ref }} | xargs -L1 verify-emoji-commit